version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis:/data
    command: redis-server --save 20 1 --loglevel warning
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo/conf:/data/configdb
      - ./database/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: app

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  backend:
    build: backend/
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis

  frontend:
    build: frontend/
    network_mode: host
    ports:
      - "8080:80"
    depends_on:
      - backend